### ISSUE TITLE
Examples should suggest using the analyzer for production bundles

### ISSUE THREAD

**Issue by knowler** [MaximVanhove/laravel-mix-bundle-analyzer#2]
It doesn’t make much sense to suggest analyzing in development when the production bundle is what really matters.

**Comment by MaximVanhove** [comment]
I only build to production on the production server. You do not have to follow my way though :)

**Comment by MaximVanhove** [comment]
@knowler You could also install the [dotenv](https://www.npmjs.com/package/dotenv) package and only fire the analyzer if the environment is set to local

**Comment by pryley** [comment]
```js
const mix = require('laravel-mix');

if (mix.inProduction()) {
    require('laravel-mix-bundle-analyzer');
    mix.bundleAnalyzer();
}
```
