### ISSUE TITLE
TypeError: mix.extend is not a function

### ISSUE THREAD

**Issue by sebsobseb** [MaximVanhove/laravel-mix-bundle-analyzer#5]
When i run `npm run dev`, I get the following error:

```
mix.extend('bundleAnalyzer', new BundleAnalyzer());
    ^

TypeError: mix.extend is not a function
    at Object.<anonymous> (/node_modules/laravel-mix-bundle-analyzer/index.js:23:5)
```

Can you please fix?

**Comment by MaximVanhove** [comment]
What is your lavavel mix version?

**Comment by sebsobseb** [comment]
@MaximVanhove 1.0

**Comment by MaximVanhove** [comment]
You should update laravel mix to at least 2.0, but 5.0 is recommended.

**Comment by sebsobseb** [comment]
I think v2.1 is the minimum, since `mix.extend()` was added in v2.1: https://github.com/JeffreyWay/laravel-mix/releases/tag/v2.1. 

Maybe an idea to add the min. requirements in the README.md 👍

**Comment by MaximVanhove** [comment]
Actually I added 4.* as peer dependency and you should have got a warning while installing with npm. But I'll also add the requirement to the readme 🙂

**Comment by MaximVanhove** [comment]
Requirements are added in `1.0.5`
